name: Obfuscate Lua Script

on:
  workflow_dispatch:

jobs:
  obfuscate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Lua
        uses: leafo/gh-actions-lua@v11   # ← เปลี่ยนจาก v10 เป็น v11
        with:
          luaVersion: "5.1.5"
      
      - name: Setup LuaRocks
        uses: leafo/gh-actions-luarocks@v4
      
      - name: Obfuscate script
        run: |
          lua cli.lua --preset Medium gg_file.lua
      
      - name: Upload obfuscated file
        uses: actions/upload-artifact@v4
        with:
          name: obfuscated-script
          path: gg_file.obfuscated.lua
